sudo: true

language: node_js

matrix:
    fast_finish: true
    include:
        - node_js: 8
          env: version=8
        - node_js: 9
          env: version=9
        - node_js: 10
          env: version=10
services:
    - postgresql  

before_install:
    - sh -c "psql -c 'create database notadd;' -U postgres;"

install:    
    - npm install yarn -g
    - yarn install
    
